Add more URLs
grantjenks/py-tree-sitter-languages pull request #33
Opened 2023-10-27 16:01 UTC by Freed-Wu

2023-10-27 16:13 UTC, grantjenks commented
Look at the past merges. You have to change more than repos.txt

2023-10-28 05:22 UTC, Freed-Wu commented
Update build.py

2023-10-28 14:41 UTC, grantjenks commented
Also the readme and the tests.

2023-10-29 10:20 UTC, Freed-Wu commented
Updated

2023-10-29 10:20 UTC, Freed-Wu commented
Related discussion: <https://github.com/nvim-treesitter/nvim-treesitter/discussions/5588>

2023-11-06 15:35 UTC, Freed-Wu commented
@grantjenks

2023-11-06 15:53 UTC, grantjenks commented
You can’t just delete all the licenses from the readme. Distributing in binary form doesn’t necessarily remove all license restrictions.

2023-11-06 16:56 UTC, Freed-Wu commented
Can we have some method to update license automatically like <https://github.com/nvim-treesitter/nvim-treesitter/discussions/5588#discussioncomment-7415038>?

2023-11-28 06:29 UTC, Freed-Wu commented
> You can’t just delete all the licenses from the readme.

I have added the licenses.

> Distributing in binary form doesn’t necessarily remove all license restrictions.

[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) doesn't add any license in README. Is it necessary?

2023-11-29 08:50 UTC, Freed-Wu commented
@grantjenks

2023-11-29 13:17 UTC, Freed-Wu commented
And, I advise to add a scheduled CI/CD to update the version.

2023-12-22 05:31 UTC, Freed-Wu commented
@grantjenks Any other problem? If you are busy to review this PR, can you add me to collaborators?

2024-01-02 19:17 UTC, grantjenks commented
Looking at the project licenses, I don't think you can add GPL'd code and maintain this project as Apache 2.

ChatGPT thinks so too: https://chat.openai.com/share/fe181dca-6ebc-4965-890e-d8ef20cfcb6b

IANAL

2024-01-03 02:12 UTC, Freed-Wu commented
> add GPL'd code and maintain this project as Apache 2.

Where is GPL's code? This project's license shouldn't be changed.

2024-01-03 17:17 UTC, grantjenks requested changes
There will need to be an ALLOWLIST of Apache2 compatible software licenses.

GPLv3 is not compatible with Apache2.

2024-01-03 17:17 UTC, grantjenks commented on README.rst
> +* https://gitlab.com/gabmus/tree-sitter-blueprint.git — licensed under the GNU General Public License v3.0
GPL'd code

2024-01-03 17:17 UTC, grantjenks commented on README.rst
> +* https://github.com/RubixDev/ebnf — licensed under the GNU General Public License v3.0
GPL'd code

2024-01-04 05:32 UTC, sansmoraxz commented
Any updates on this?

2024-01-04 16:00 UTC, sansmoraxz commented
Could you move the hashes of the repo to stable commit (or the commit with latest release attached if possible). I don't think all of them are stable.

2024-01-04 21:25 UTC, sansmoraxz commented
Also a lot of them are missing `src/parser.c`. (Written in JS)

Those will fail to build.

2024-01-20 16:33 UTC, Freed-Wu commented
> a lot of them are missing src/parser.c

Not sure why missing. Let us delete them before we know why.

2024-01-20 16:34 UTC, Freed-Wu commented
> There will need to be an ALLOWLIST of Apache2 compatible software licenses.

How to get the allowlist?

2024-02-17 10:09 UTC, Freed-Wu commented
There are many languages information is stored in <https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua#L79-L2269> and updated very frequently.
We should have a method to extract them to get the latest parsers.

2024-02-17 10:09 UTC, closed without merging

2024-02-17 11:57 UTC, sansmoraxz commented
Is it really a better approach though?

I find locking down to commit id's to be a much more sensible option.